# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
#\3 See also: https://github.com/marketplace/actions/bazel-action

name: Nightly Fuzz
on: [push]
jobs:
  build:
    name: Nightly Fuzz
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Mount Bazel Cache
        uses: actions/cache@v2
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Install dependencies via apt
        run: sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
      - name: Bazel Build Fuzz Driver (opt)
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build -c opt xls/fuzzer:run_fuzz_multiprocess
      - name: Bazel Run Fuzz (nosim, opt)
        # TODO(leary): 2020-08-28 Can remove some of these "lighter weight"
        # options as we understand why GitHub action jobs are getting killed.
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" run -c opt xls/fuzzer:run_fuzz_multiprocess -- --crash_path "${GITHUB_WORKSPACE}/crashers" --sample_count=1024 --codegen=false --simulate=false --short_samples=false --emit_loops=False --summary_path "${GITHUB_WORKSPACE}/crashers"
      - name: Upload Fuzz Crashers
        uses: actions/upload-artifact@v2
        with:
          name: crashers
          path: "${GITHUB_WORKSPACE}/crashers"
